#function for deleting dir structure created by function startdir

#' Delete directory structure inside of project folder, which was generated by startdir function.
#'
#' @param "package" or "analysis"
#' @return delete directory structure eather in format \code{"package"} or \code{"analysis"}.
#' @seealso (\code{\link{startdir}})
#' @examples
#' undir("package")
undir <- function (type=c("package", "analysis")) {
  if (type == "package") {
    package <- c("src","tests", "vignettes","inst", "inst/templates", "man")
    sapply (package, unlink, recursive=TRUE)
  } else if (type== "analysis") {
    analysis <- c("articl","data", "exports","R")
    sapply (analysis, unlink, recursive=TRUE)
  } else {
    print ("ERROR")
  }

}
